config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :articles do
    resources :comments
  end
  resources :contacts 
  root to: 'pages#index'
  get 'pages/contact'
  get 'pages/about'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :update, Article do |article|
          article.user == user
        end
        
        can :destroy, Article do |article|
          article.user == user
        end
        can :update, Comment do |comment|
          comment.user == user
        end
        
        can :destroy, Comment do |comment|
          comment.user == user
        end  
        
        can :create, Article
        can :create, Comment
        can :read, :all
      end
    
   
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, length: { minimum: 5, maximun: 120 }
  validates :title, uniqueness: true, uniqueness: {message: "This article title has already been posted."}
  validates :body, length: { minimum: 15 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  
  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :message
 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_uniqueness_of :username
         
  has_many :articles
  has_many :comments 
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, 
  default_url: "https://s3.amazonaws.com/rorpost/536989_10151266339362308_1763871769_n.jpg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
   rescue_from CanCan::AccessDenied do |exception|
     redirect_to root_path
     flash[:danger] = "Sorry, you are not authorized to access this area!"
 end


end


  

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5).order('created_at DESC')
    @last5 = Article.order('created_at DESC').last(5)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = current_user.articles.build
  end

  # GET /articles/1/edit
  def edit
    authorize! :update, @article
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    authorize! :update, @article
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    authorize! :destroy, @article
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource param_method: :my_sanitizer
  load_and_authorize_resource :through => :current_user
  
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(params[:comment].permit(:body))
    @comment.user_id = current_user.id if current_user
    
    
    if @comment.save
      redirect_to article_path(@article), notice: "Your comment has been saved."
    else
      redirect_to @article
      flash[:warning]= "Tehere was a problem saving your comment, Minimum length is 5 character adn the Max is 500."
  end
end
  
  def update
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    
    if @comment.update(params[:comment].permit(:body))
      redirect_to article_path(@article), notice: "Your comment has been updated."
    else
      render 'edit'
    end
  end
  
  def edit
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
  end
  
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), notice: "Your comment has been deleted."
  end
  
   private

  def my_sanitizer
    params.require(:commet).permit(:body)
  end

  
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def new
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(contact_params)
    
      if @contact.save
        redirect_to root_path
        name = params[:contact][:name]
        email = params[:contact][:email]
        message = params[:contact][:message]
        ContactMailer.contact_email(name, email, message).deliver
        flash[:success] = "Thanks for the message, we will be in touch soon."
      else
        redirect_to pages_contact_path
        flash[:danger] = "Opps, there was a problem! Please fill out all the fields."
        
      end
  end
  
  
  
    private
    
    def contact_params
      params.require(:contact).permit(:name, :email, :message)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  
  def index
    if current_user
      redirect_to articles_path
    end
    @articles = Article.paginate(page: params[:page], per_page: 5).order('created_at DESC')
  end

  def contact
  @contact = Contact.new  
  end

  def about
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(
      :email, 
      :password, 
      :password_confirmation,
      :username,
      :firstname,
      :lastname,
      :image,
      :url
      )
  end

  def account_update_params
    params.require(:user).permit(
      :email, 
      :password, 
      :password_confirmation, 
      :current_password,
      :username,
      :firstname,
      :lastname,
      :image,
      :url
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title, label: false, placeholder: "Article title" %>
    <%= f.input :body, label: false, placeholder: "Body title" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-success" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="row">
    <!-- Blog article Content Column -->
    <div class="col-lg-8">
<% @articles.each do |article| %>
        <!-- Blog article -->

        <!-- Title -->
        <h4 style="font-size: 25.5px;"><%= link_to article.title, article %></h4>
                        <!-- Date/Time -->

        
        <%= image_tag article.user.image.url(:thumb), class: "img-circle" %>


        <p><span class="glyphicon glyphicon-time"></span> 
           <%= time_ago_in_words(article.created_at)%> ago 
        </p>
        
        
        <!-- Author -->
        <p>
             Article By:<strong>  <%=  article.user.username %></strong>
        </p>

        <hr>

        <!-- articleed Comments -->

        <!-- Comment -->

<% end %>

<%= link_to "New article", new_article_path, class: "btn btn-primary btn-xs" %>

    </div>

<!-- Blog Sidebar Widgets Column -->
<div class="col-md-4">
    <div class="well">
          <h4>Recent articles</h4>
            <% @last5.each do |a| %>
              Created by: <%= a.user.username %><br />
              <strong><%= link_to truncate(a.title, length: 35), a %></strong>
              <p><%= truncate(a.body) %></p>
            <% end %>
    </div>
</div>

</div>

<%= will_paginate @articles %>
<br>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class="row">

    <!-- Blog Post Content Column -->
    <div class="col-lg-8">

        <!-- Blog Post -->

        <!-- Title -->
        <h1 style="font-size: 25.5px;">  
         <%= @article.title %>
        </h1>

        <!-- Author -->
        <p class="lead">
          Article by: <%= @article.user.username %>
        </p>
        <%= image_tag @article.user.image.url(:thumb), class: "img-circle" %>
        <hr>

        <!-- Date/Time -->
        <p><span class="glyphicon glyphicon-time"></span> Was posted about <%= time_ago_in_words(@article.created_at)%> ago 
     

        <hr>

        <!-- Preview Image -->
        

        <!-- Post Content -->
          <%= @article.body %>
       
        <hr>

        <!-- Blog Comments -->
<%= render @article.comments %>
        <!-- Comments Form -->
       
        <%= render 'comments/form' %>  
        <div class="well">
          

<h4></h4>


        </div>

        <hr>

        <!-- Posted Comments -->

        <!-- Comment -->



    </div>

    <!-- Blog Sidebar Widgets Column -->
    <div class="col-md-4">

        <!-- Blog Search Well -->
        

        <!-- Blog Categories Well -->
        

        <!-- Side Widget Well -->
        <div class="well">
          <h4></h4>
  
        </div>

    </div>

</div>

<%= link_to 'Back', articles_path, class: "btn btn-success btn-xs round" %>


<% if can? :update, @article %>|
<%= link_to 'Edit Article', edit_article_path(@article), class: "btn btn-info btn-xs round" %> 
<% end %>


<% if can? :destroy, @article %>
<%= link_to 'Delete Article', @article, method: :delete, data: {confirm: 'Are you sure you want to delete this article?' }, class: "btn btn-danger btn-xs round" %>
<% end %>

app/views/comments/_comment.html.erb
<div class="color round2">
<div class="media">
    
    <div class="pull-left">
        
        <strong>Comment by <%= comment.user.username %></strong>
        
       
    </div>
    <br/>
    
    <div class="media-body">
        <p class="media-heading pull-right">
          <%= time_ago_in_words(comment.created_at) %> ago <br /> <%= image_tag comment.user.image.url(:thumb), class: "img-circle" %>
        </p><br />
        
        <%= comment.body %>
       
    </div>
    <dr/>
</div>
<br/>
<% if can? :update, comment %>

	<%= link_to "Edit Comment", edit_article_comment_path(comment.article, comment), class: "btn btn-info btn-xs round" %>
	
<% end %>
	
<% if can? :destroy, comment %>

<%= link_to "Delete Comment", [comment.article, comment], method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-xs round" %>

<% end %>
</div>
<br/>

app/views/comments/_form.html.erb
<%= simple_form_for ([@article, @article.comments.build]) do |f| %> 

<%= f.input :body, label: false, placeholder: "Enter a comment." %>
<%= f.submit "Post your comment" %>

<% end %>

app/views/comments/edit.html.erb
<h1> Edit Comment</h1>

<%= simple_form_for([@article, @comment]) do |f| %>
	<%= f.input :body %>
	<%= f.submit %>
	
	<% end %>

app/views/layouts/_foot.html.erb
<footer class="footer-distributed navbar-fixed-bottom">

	<div class="footer-right">

		<a href="#"><i class="fa fa-facebook"></i></a>
		<a href="#"><i class="fa fa-twitter"></i></a>
		<a href="#"><i class="fa fa-linkedin"></i></a>
		<a href="#"><i class="fa fa-github"></i></a>

	</div>

	<div class="footer-left">

		<p class="footer-links">

			·
			<%= link_to "Contact Us", pages_contact_path, class: "page-scroll" %>	
			·
			<%= link_to "About Us", pages_about_path, class: "page-scroll" %>	
			·

		</p>

<p>   </p>
</div>

</footer>


		

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Checha's Articles", root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
        
        <li><%= link_to "Contact Us", pages_contact_path %></li>
        <li><%= link_to "About Us",  pages_about_path %></li>
        <li><%= link_to "View Articles",  articles_path %></li>
        
      <% if !current_user %>
      
        <li><%= link_to "Sign Up", new_user_registration_path  %></li>
        <li><%= link_to "Sign in",  new_user_session_path  %></li>
        
        <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" 
          aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><%= link_to "Edit My Profile", edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Checha's Articles</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/nav' %>
 <%= bootstrap_flash %>
<div class='container'>
  <%= yield %>
</div>

<%= render 'layouts/foot' %>

</body>
</html>

app/views/pages/_mailer.html.erb
 <div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="well">
        <%= simple_form_for @contact do |f| %>
        <%= f.input :name %>
        <%= f.input :email %>
        <%= f.input :message %>
        <%= f.submit "Get in touch!", class: "btn btn-info" %>
        <% end %>
    </div>
  </div>
</div>

app/views/pages/about.html.erb
<div class="row">
    <div class="col-lg-12 text-center">
        <h1>About Us</h1>
        <p class="lead">Test Text</p>
        <ul class="list-unstyled">
            <li>List Item</li>
            <li>List Item 2</li>
        </ul>
    </div>
</div>

app/views/pages/contact.html.erb
<div class="row">
  <div class="col-lg-12 text-center">
      <h1>Contact Us</h1>
      <p class="lead">Test Text</p>
      <ul class="list-unstyled">
          <li>List Item</li>
          <li>List Item 2</li>
      </ul>
  </div>
  <%= render 'pages/mailer' %>
</div>

app/views/pages/index.html.erb
<div class="row">
  <div class="col-lg-8">

        <!-- Blog Post -->

        <!-- Title -->
<div class="jumbotron">
  <h1 class="text-center">Welcome to Checha's Articles.  </h1>
  <p class="text-center">Awesome applications built with Rails!</p>
  <p></p>
</div>

       


    </div>

    <!-- Blog Sidebar Widgets Column -->
    <div class="col-md-4">


        <!-- Blog Categories Well -->


        <!-- Side Widget Well -->
        <div class="well">
          <h4>Recent Posts</h4>
            <% @articles.each do |a| %>
              Created by: <%= a.user.username %><br />
              <strong><%= link_to truncate(a.title, length: 35), a %></strong>
              <p><%= truncate(a.body) %></p>
            <% end %>
        </div>

    </div>

</div>
<!-- /.row -->

<hr>